---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: moodle
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.4
    path: /bitnami
  mountOptions:
    - rw
    - hard
    - rsize=1048576
    - wsize=1048576
    - sec=sys
    - vers=4.1
    - tcp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: moodle
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi