version: '2.4'

services:
  moodle:
    image: robecehub/moodle:1.0.38
    #build:
    #  context: 3-debian-10
    #  dockerfile: Dockerfile
    hostname: moodle
    environment:
    
      # Debug and tracing
      - NAMI_DEBUG=--log-level=trace

       # Database
      - MOODLE_DATABASE_TYPE=mysqli # set mariadb or mysqli
      - MARIADB_HOST=moodledb02.mysql.database.azure.com
      - MARIADB_PORT_NUMBER=3306

      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=Password.123

      # User and Site Configuration
      - MOODLE_SITE_NAME=NewSite
      - MOODLE_EMAIL=user@email.com
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Password.123

      # PHP Environment Variables
      - PHP_MEMORY_LIMIT=250M

      # Installation (set no for first time database configuration, yes to connect to previously configured database)
      - MOODLE_SKIP_INSTALL=yes
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - .\volume\moodle:/bitnami/moodle
      - .\volume\moodledata:/bitnami/moodledata
