version: '2.4'

services:
  mariadb-server:
    image: bitnami/mysql:5.7
    hostname: mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD='[database root password]'
      - MYSQL_USER='[database user]'
      - MYSQL_PASSWORD='[database password]'
      - MYSQL_DATABASE='[database name]'
    volumes:
      - .\volume\mysql:/bitnami